

services:
  db:
    image: postgres:15-alpine
    container_name: words_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-words_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: .
    container_name: words_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DB_NAME: ${POSTGRES_NAME:-words_db}
      DB_MIGRATE_PATH: ${MIGRATE_PATH:-file://migrations}
      API_PORT: ${API_PORT:-8080}
    depends_on:
      - db
    networks:
      - backend
volumes:
  db-data:
networks:
  backend: